### ISSUE TITLE
Problem with logging...

### ISSUE THREAD

**Issue by equinox0815** [fabric8io/elasticsearch-cloud-kubernetes#41]
Hi,

I'm currently working on a small test setup based on Elasticsearch 2.3.4 with this plugin running on Kubernetes 1.3. For some reason the plugin can't connect to the API server or at least it doesn't feed any endpoints into Elasticsearch. It might have something to do with the fact that we use client certificates to authenticate against the Kubernetes API server but i can't confirm this because the logging isn't working properly.
I'm using the following `logging.yml` for elasticsearch:

```
# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: INFO
rootLogger: ${es.logger.level}, console
logger:
  # log action execution errors for easier debugging
  action: DEBUG

  org.apache.http: INFO

  # gateway
  #gateway: DEBUG
  #index.gateway: DEBUG

  # peer shard recovery
  #indices.recovery: DEBUG

  # discovery
  io.fabric8: TRACE

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
```

For some reason i only get logging output from the plugin itself but not from the underlaying KubernetesClient Plugin.
Is there something wrong with the way i configure the logging in Elasticsearch? I already tried to set  `es.logger.level` to `DEBUG` but still no output from the Kubernetes Client.

Thanks in advance for you help!

regards
  christian
