### ISSUE TITLE
ElasticSearch fabric8 plugin does not use K8s SA for API requests

### ISSUE THREAD

**Issue by dragonsmith** [fabric8io/elasticsearch-cloud-kubernetes#93]
Hello,

I'm trying to get ES 5.4.2 cluster to work on my K8s setup.

Here is the actual configuration:

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: elasticsearch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: elasticsearch
  namespace: elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: elasticsearch
  namespace: elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: elasticsearch

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: elastic-cluster
  namespace: elasticsearch
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
    component: elasticsearch

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elasticsearch
data:
  elasticsearch.yml: |
    ---
    cluster.name: elasticsearch
    network.host: 0.0.0.0

    cloud:
      kubernetes:
        service: elastic-cluster
        namespace: elasticsearch

    discovery:
      zen:
        hosts_provider: kubernetes

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
    component: elasticsearch
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
      component: elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        component: elasticsearch
      name: elasticsearch
    spec:
      serviceAccount: elasticsearch
      serviceAccountName: elasticsearch
      nodeSelector:
        elasticsearch-node: "true"
      containers:
        - image: quay.io/evilmartians/elasticsearch-k8s:5.4.2
          name: elasticsearch
          ports:
          - containerPort: 9200
            name: "http"
          - containerPort: 9300
            name: "transport"
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            name: elasticsearch-config-volume
            subPath: elasticsearch.yml
          resources:
            limits:
              cpu: "1"
              memory: 3500Mi
            requests:
              cpu: 500m
              memory: 700Mi
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
          - vm.max_map_count=10485761
      volumes:
      - configMap:
          name: elasticsearch-config
        name: elasticsearch-config-volume
```

I've used the image I've built by myself using [Dockerfile](https://github.com/evilmartians/elasticsearch-k8s/blob/master/Dockerfile) As the original `fabric8/elasticsearch-k8s:5.4.2` fails to load some java classes with the configuration above.

I'm getting only one line of log messages from fabric8 plugin:

```
elasticsearch-0 elasticsearch [2017-07-04T13:16:00,278][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [yq9KlQs] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.

elasticsearch-1 elasticsearch [2017-07-04T13:16:10,706][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [IlfXMMH] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
```

That's all.

Kubernetes API server audit.log says plugin does not even try to use the ServiceAccount I've created:

```
AUDIT: id="f06e30d1-ba2d-4ade-9d32-a716a0a37592" ip="127.0.0.1" method="GET" user="<none>" groups="<none>" as="<self>" asgroups="<lookup>" namespace="wazuh" uri="/api/v1/namespaces/wazuh/endpoints/elastic-cluster"
```

Of course I can test my SA with curl manually(just to be sure it works fine):

```shell
curl --stderr /dev/null --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://192.168.128.1/api/v1/namespaces/wazuh/endpoints/elastic-cluster

{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "elastic-cluster",
    "namespace": "wazuh",
    "selfLink": "/api/v1/namespaces/wazuh/endpoints/elastic-cluster",
    "uid": "c104ab17-5ca2-11e7-810f-2a5a76cb5f8b",
    "resourceVersion": "55557470",
    "creationTimestamp": "2017-06-29T08:12:55Z"
  },....
}
```

And here is how the correct request looks like in audit.log:

```
2017-07-04T16:38:22.618122102+03:00 AUDIT: id="58a92f82-6c68-43e2-a2b3-c4d01c9542b5" ip="10.129.24.57" method="GET" user="system:serviceaccount:wazuh:wazuh" groups="\"system:serviceaccounts\",\"system:serviceaccounts:wazuh\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="wazuh" uri="/api/v1/namespaces/wazuh/endpoints/elastic-cluster"
```

Please, help me dig further to solve this problem. I'm kinda out of ideas.

Thank you very much!

**Comment by gavk34** [comment]
I am seeing something similar
```
[2018-05-11T07:19:54,357][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-logging-0] Exception caught during discovery: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/monitoring/endpoints/elasticsearch-logging. Cause: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
```

The following is my role bindings etc.
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: elasticsearch
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: elasticsearch
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: monitoring
```

And as per logged issue, curl for the api request works. Any ideas?
